name: master_html
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.6
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  device_info_plus: ^8.1.0
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  share_plus: ^6.3.2
  path_provider: ^2.0.14
  widgets_to_image: ^0.0.2
  flutter_html: ^3.0.0-alpha.6
  google_mobile_ads: ^3.0.0
  connectivity_plus: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
flutter_native_splash:
  color: "#000000"
#  branding: assets/branding_logo.png
  image: assets/splash_logo.png

flutter_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#0f162b"

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lesson_photos/

 #Fonts
  fonts:
  #This is the default text theme also used in the fonts list ;
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #This font is used in the app but not in the fonts list
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  #This font is used on "Facebook" text only ;
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
  #These fonts are only used in the font family lists
    - family: Averia
      fonts:
        - asset: assets/fonts/AveriaSansLibre-Regular.ttf

    - family: Expletus
      fonts:
        - asset: assets/fonts/ExpletusSans-Regular.ttf

    - family: Spline
      fonts:
        - asset: assets/fonts/SplineSansMono-Regular.ttf
