final List<String> AllLessonsList = [
  'HTML Introduction',
  'Code Editor',
  'HTML Boilerplate',
  'HTML Elements',
  'HTML Attributes',
  'HTML Comments',
  'HTML Headings',
  'HTML Paragraphs',
  'HTML Styling',
  'HTML images',
  'HTML Links',
  'HTML Line Breaks',
  'HTML Horizontal Rule',
  'HTML Text Formatting',
  'Semantic HTML',
  'Semantic HTML part 2',
  'HTML Block vs Inline Elements',
  'HTML Sections',
  'HTML Articles',
  'HTML Tables',
  'HTML Lists',
  'HTML Dropdown Lists',
  'HTML File Paths',
  'HTML Forms',
  'HTML Form Labels',
  'HTML Input',
  'HTML Input Part 2',
  'HTML Input part 3',
  'HTML Form Attributes',
  'HTML Form Attributes part 2',
  'HTML Textarea',
  'HTML Buttons',
  'HTML Editable Contents',
  'HTML Meta Tags',
  'HTML Fonts',
  'HTML Subscript Text',
  'Html Superscript Text',
  'HTML nbsp',
  'HTML Figures',
  'HTML Character Entities',
  'HTML Videos',
  'HTML Audios',
  'HTML Pictures',
  'HTML Iframe',
  'HTML Iframe part 2',
  'HTML Entities',
  'HTML SVG',
  'HTML Canvas',
  'HTML Vs XHTML',
  'What\'s next?'
];
